apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-proxy
    spec:
      containers:
       # Make sure to specify image tag in production
       # Check out the newest version in release page
       # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
      - image: b.gcr.io/cloudsql-docker/gce-proxy:1.05
       # 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
        name: postgres-proxy
        command: ["/cloud_sql_proxy", "-dir=/cloudsql",
                  "-instances=coherent-window-177723:isba-db=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-oauth-credentials
          readOnly: true
        - mountPath: /cloudsql
          name: cloudsql
        - mountPath: /etc/ssl/certs
          name: ssl-certs
      volumes:
      - name: cloudsql-oauth-credentials
        secret:
          secretName: cloudsql-oauth-credentials
      - name: cloudsql
        emptyDir:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
