apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ispa
  labels:
    name: ispa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ispa
    spec:
      containers:
        - name: ispa
          image: "gcr.io/ispa-176718/github-aleccunningham-ispa:1819e177fa46c3bb1e9858176146f44b0b574a34"
          workingDir: /home/docker/ispa
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password
