apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ispa
  labels:
    name: ispa
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: ispa
    spec:
      containers:
        - name: ispa
          image: "gcr.io/ispa-176718/github-aleccunningham-ispa:1819e177fa46c3bb1e9858176146f44b0b574a34"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPatch: /etc/secrets
              readOnly: true
          volumes:
            - name: secrets
              secret:
                secretName: db-passwords
