---
apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
data:
  djangouserpw: {{ db_pass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistantVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: {{ gce_disk_ name }}
    fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  templates:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: gcr.io/ispa-176718/postgres-pw
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresdata
              mountPath: /usr/local/var/postgres
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-data
        - name: secrets
          secret:
            secretName: db-passwords
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    selector:
      name: postgres
