apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ispa-app
  labels:
    app: ispa-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ispa-app
    spec:
      containers:
      - image: gcr.io/rapid-smithy-177819/ispa
        name: ispa-app
        imagePullPolicy: Always
        command: ["/gunicorn.sh"]
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql
                key: password
        ports:
          - containerPort: 8080
