apiVersion: v1
kind: Service
metadata:
  name: redispack
  labels:
    app: redispack
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    port: 26379
    targetPort: 26379
    protocol: TCP
  selector:
    app: redispack
